---
title: "Optimization"
author: "issa fall"
date: "September 7, 2015"
output: html_document
---

## Maximizing a normal likelihood
```{r,echo=TRUE}
make.Negloglik<-function(data,fixed = c(FALSE,FALSE)){
             params<-fixed
             function(p){
               params[!fixed]<-p
               mu<-params[1]
               sigma<-params[2]
               a<--0.5*length(data)*log(2*pi*sigma^2)
               b<--0.5*sum((data-mu)^2)/(sigma^2)
               -(a+b)
             }
}
```
##Note that optimization functions in R minimize functions,so you need to use the
##negative log-likelihood.
```{r,echo=TRUE}
set.seed(1)
normals<-rnorm(100,1,2)
nLL<-make.Negloglik(normals)
nLL
ls(environment(nLL))
```
##Estimating parameters
```{r,echo=TRUE}
optim(c(mu =0,sigma =1),nLL)$params
```
##Fixing sigma=2
```{r,echo=TRUE}
nLL<-make.Negloglik(normals,c(FALSE,2))
optimize(nLL,c(-1,3))$minimum
```
##Fixing mu=1
```{r,echo=TRUE}
nLL<-make.Negloglik(normals,c(1,FALSE))
optimize(nLL,c(1e-6,10))$minimum
```
##Plotting the likelihood
```{r,echo=TRUE}
nLL<-make.Negloglik(normals,c(1,FALSE))
x<-seq(1.7,1.9,len=100)
y<-sapply(x,nLL)
plot(x,exp(-(y-min(y))))
nLL<-make.Negloglik(normals,c(FALSE,2))
x<-seq(0.5,1.5,len=100)
y<-sapply(x,nLL)
plot(x,exp(-(y-min(y))))
```


## Matrix function
```{r,echo=TRUE}

x<-matrix(1:6, 2,3)
  for(i in seq_len(nrow(x))){
    for(j in seq_len(ncol(x))){
      print(x[i,j])
    }
  }

x
```